version: "3.8"

services:

  order-ms:
    container_name: order-ms
    image: order-ms
    restart: always
    build:
      context: .
      dockerfile: order-ms/Dockerfile
      args:
        - BASE_DIR=order-ms
    env_file:
      - ./order-ms/.env
    ports:
      - "3500:3500"
    networks:
      - net-ms-order
    depends_on:
      - mongo-order
      - rabbitmq

  mongo-order:
    image: mongo:3.6
    container_name: mongo-order
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-vol-order:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    networks:
      - net-ms-order

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - net-ms-order

volumes:
  mongo-vol-order:


networks:
  net-ms-order:


